apiVersion: v1
kind: Service
metadata:
  name: commandline-js-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    role: commandline-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: commandline-app-deployment
  labels:
    role: commandline-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: commandline-app
    spec:
      containers:
      - name: commandline-js-container
        image: eu.gcr.io/desarrollar-180407/commandline-js
        imagePullPolicy: Always
        ports:
            - containerPort: 3000